version: '3'
services:
    bookapi:
        build:
            context: ./app
            dockerfile: ./Dockerfile
        command: bash -c "python manage.py migrate && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "9080:8000"
        restart: "no"

networks:
    default:
        external:
            name: localcommonnetwork1

# manually run this before creating containers:
#   docker network create localcommonnetwork1